import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Banner from "@/component/Banner";
import Footer from "@/component/Footer";
import { PersonalizationProvider } from "@/context/PersonalizationProvider";
import { LanguageProvider } from "@/context/Languagecontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LanguageProvider initialLocale="en-us">
          <PersonalizationProvider>
            <Header />
            <Banner />
            {/* {children} */}
            <Footer />
          </PersonalizationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
